openapi: 3.0.3
info:
  title: Know Your Customer Fill-in

  description: |

    This API provides the customer with the ability request and receive the information for a particular user, which on file (and verified) by the user's Operator in their own KYC records, in order for the SP to confirm the accuracy of the information and provide a specific service to the user.

    ## Relevant Definitions and concepts

    * **KYC**: stands for Know Your Customer and it is the process of a business verifying the identity of their clients and assessing their suitability, along with the potential risks of illegal intentions towards the business relationship.

    ## API Functionality

    This API allows API clients to request for API provider / MNO to provide information related to a mobile phone user, derived from the account data bound to their phone number.  The API is intended to be used in the following scenario, for example:

    * To fill-in the user personal data during the digital registration of an account to a 3rd party service.

    Note:

    * Before calling this API, 3rd parties / enterprise customers who want to use this API should make contract with API provider/ Operator for use of this API.  As that will depend on each API provider / MNO's business processes as well as GSMA Open Gateway standard process, it is out of scope of this API definition.

    * When calling this API, at the beginning, there should be required processes for Authentication / Authorisation / End User Consent capturing.  As those processes are to be defined as CAMARA commonality standards, they are out of scope of this API definition, however, use of the OpenID Connect (OIDC) is stated as security scheme.  **As an important note**, capturing end user consent is necessary, because this API provides end user information (PII).

    * The above mentioned AuthN/AuthZ/End User consent capturing processes can give the API provider/ MNO the 3rd party identity (with the Access Token) and the end user identity (with the ID Token), so the API provider/ MNO can identify the 3rd party / enterprise customer and the end user.  Then, it is up to API provider/ MNO to decide which information the 3rd party will receive by calling the API, and also the API provider / MNO is responsible for security and privacy issues.

    * For example, below is a potential operation:
      * when making contract with API provider/ MNO, a 3rd party / enterprise customer receives its 3rd party identity and also decide which information (attributes) it will receive for its API call
      * then, API provider / MNO will provide information (attributes) which the 3rd party / enterprise customer is allowed to receive by the contract.

    ### Special Scopes

    This API uses the following special scope `kyc-fill-in:set-all` which means that the API provider returns an API response as if all these scopes were specified in the scope value in the request:

    `kyc-fill-in:phoneNumber kyc-fill-in:idDocument kyc-fill-in:idDocumentType kyc-fill-in:idDocumentExpiryDate kyc-fill-in:bankAccountNumber kyc-fill-in:name kyc-fill-in:givenName kyc-fill-in:familyName kyc-fill-in:nameKanaHankaku kyc-fill-in:nameKanaZenkaku kyc-fill-in:middleNames kyc-fill-in:familyNameAtBirth kyc-fill-in:address kyc-fill-in:streetName kyc-fill-in:streetNumber kyc-fill-in:postalCode kyc-fill-in:region kyc-fill-in:locality kyc-fill-in:country kyc-fill-in:houseNumberExtension kyc-fill-in:birthdate kyc-fill-in:email kyc-fill-in:gender kyc-fill-in:cityOfBirth kyc-fill-in:countryOfBirth kyc-fill-in:nationality`

    ## Resources and Operations overview

    The API provides the following endpoint:

    * An endpoint to request information related to an end user against the account data bound to their phone number.

    <!-- CAMARA:MANDATORY:authorization-and-authentication:BEGIN -->
    # Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details of how an API consumer requests an access token. Please refer to Identity and Consent Management (https://github.com/camaraproject/IdentityAndConsentManagement/) for the released version of the profile.

    The specific authorization flows to be used will be agreed upon during the onboarding process, happening between the API consumer and the API provider, taking into account the declared purpose for accessing the API, whilst also being subject to the prevailing legal framework dictated by local legislation.

    In cases where personal data is processed by the API and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of three-legged access tokens is mandatory. This ensures that the API remains in compliance with privacy regulations, upholding the principles of transparency and user-centric privacy-by-design.
    <!-- CAMARA:MANDATORY:authorization-and-authentication:END -->

    # Identifying the phone number from the access token

    This API requires the API consumer to identify a phone number as the subject of the API as follows:
    - When the API is invoked using a two-legged access token, the subject will be identified from the optional `phoneNumber` field, which therefore MUST be provided.

    - When a three-legged access token is used however, this optional identifier MUST NOT be provided, as the subject will be uniquely identified from the access token.

    This approach simplifies API usage for API consumers using a three-legged access token to invoke the API by relying on the information that is associated with the access token and was identified during the authentication process.

    ## Error handling:
    - If the subject cannot be identified from the access token and the optional `phoneNumber` field is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER` error code.

    - If the subject can be identified from the access token and the optional `phoneNumber` field is also included in the request, then the server will return an error with the `422 UNNECESSARY_IDENTIFIER` error code. This will be the case even if the same phone number is identified by these two methods, as the server is unable to make this comparison.

    <!-- CAMARA:MANDATORY:additional-error-responses:BEGIN -->
    # Additional CAMARA error responses

    The list of error codes in this API specification is not exhaustive. Therefore the API specification MAY not document some non-mandatory error statuses as indicated in `CAMARA API Design Guide`.

    Please refer to the `CAMARA_common.yaml` of the Commonalities Release associated to this API version for a complete list of error responses. The applicable Commonalities Release can be identified in the `API Readiness Checklist` document associated to this API version.

    As a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible error response if it is explicitly documented in the API.
    <!-- CAMARA:MANDATORY:additional-error-responses:END -->

    <!-- CAMARA:MANDATORY:request-body-strictness:BEGIN -->
    # Request body strictness

    This API rejects requests with JSON request bodies that contain properties not declared in this specification, at any nesting level. Unknown properties result in a `400 INVALID_ARGUMENT` response.
    <!-- CAMARA:MANDATORY:request-body-strictness:END -->

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

  version: wip
  x-camara-commonalities: 0.6

externalDocs:
  description: Product documentation at CAMARA.
  url: https://github.com/camaraproject/KnowYourCustomerFill-in

servers:
  - url: '{apiRoot}/kyc-fill-in/vwip'

    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root, defined by the service provider, e.g. `api.example.com` or `api.example.com/somepath`

tags:
  - name: Fill-in
    description: Operations to provide information related to a customer identity stored the account data bound to the customer's phone number.

paths:
  /fill-in:
    post:
      tags:
        - Fill-in
      summary: Providing information related to a customer identity stored the account data bound to the customer's phone number.
      description: |
        Provides information related to a customer identity stored the account data bound to the customer's phone number.

      operationId: kycFillin

      security:
        - openId:
            - kyc-fill-in:set-all
        - openId:
            - kyc-fill-in:phoneNumber
        - openId:
            - kyc-fill-in:idDocument
        - openId:
            - kyc-fill-in:idDocumentType
        - openId:
            - kyc-fill-in:idDocumentExpiryDate
        - openId:
            - kyc-fill-in:bankAccountNumber
        - openId:
            - kyc-fill-in:name
        - openId:
            - kyc-fill-in:givenName
        - openId:
            - kyc-fill-in:familyName
        - openId:
            - kyc-fill-in:nameKanaHankaku
        - openId:
            - kyc-fill-in:nameKanaZenkaku
        - openId:
            - kyc-fill-in:middleNames
        - openId:
            - kyc-fill-in:familyNameAtBirth
        - openId:
            - kyc-fill-in:address
        - openId:
            - kyc-fill-in:streetName
        - openId:
            - kyc-fill-in:streetNumber
        - openId:
            - kyc-fill-in:postalCode
        - openId:
            - kyc-fill-in:region
        - openId:
            - kyc-fill-in:locality
        - openId:
            - kyc-fill-in:country
        - openId:
            - kyc-fill-in:houseNumberExtension
        - openId:
            - kyc-fill-in:birthdate
        - openId:
            - kyc-fill-in:email
        - openId:
            - kyc-fill-in:gender
        - openId:
            - kyc-fill-in:cityOfBirth
        - openId:
            - kyc-fill-in:countryOfBirth
        - openId:
            - kyc-fill-in:nationality

      parameters:
        - $ref: '../common/CAMARA_common.yaml#/components/parameters/x-correlator'

      requestBody:
        required: true
        content:
          application/json:

            schema:
              $ref: '#/components/schemas/KycFillinRequest'
            examples:
              KYC_FillInBodyExample:
                value:
                  {"phoneNumber": "+34629255833"}

      responses:
        '200':
          description: OK
          headers:
            x-correlator:
              $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KycFillinResponse'
              examples:
                KYC_Fillin200Example:
                  value:
                    phoneNumber: '+34629255833'
                    idDocument: 66666666q
                    idDocumentType: passport
                    idDocumentExpiryDate: '2027-07-12'
                    bankAccountNumber: IBAN:NL59ABNA0123456789
                    name: Federica Sanchez Arjona
                    givenName: Federica
                    familyName: Sanchez Arjona
                    nameKanaHankaku: federica
                    nameKanaZenkaku: Ｆｅｄｅｒｉｃａ
                    middleNames: Sanchez
                    familyNameAtBirth: YYYY
                    address: Tokyo-to Chiyoda-ku Iidabashi 3-10-10
                    streetName: Nicolas Salmeron
                    streetNumber: '4'
                    postalCode: '1028460'
                    region: Tokyo
                    locality: ZZZZ
                    country: JP
                    houseNumberExtension: '36'
                    birthdate: '1978-08-22'
                    email: abc@example.com
                    gender: MALE
                    cityOfBirth: Madrid
                    countryOfBirth: ES
                    nationality: ES

        "400":
          $ref: '#/components/responses/Generic400'
        "401":
          $ref: '#/components/responses/Generic401'
        "403":
          $ref: '#/components/responses/Generic403'
        "404":
          $ref: '#/components/responses/Generic404'
        "422":
          $ref: '#/components/responses/Generic422'

components:
  securitySchemes:
    openId:
      description: OpenID Connect authentication
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration

  schemas:
    Iso3166Alpha2:
      type: string
      format: iso3166-1-alpha-2
      description: Two-letter ISO 3166-1 alpha-2 country code
      pattern: ^[A-Za-z]{2}$
      minLength: 2
      maxLength: 2
      example: "DE"

    KycFillinRequest:
      type: object
      description: KYC Fill-In request body
      properties:
        phoneNumber:
          $ref: "../common/CAMARA_common.yaml#/components/schemas/PhoneNumber"

    KycFillinResponse:
      type: object
      description: KYC Fill-In response body
      properties:

        phoneNumber:
          $ref: "../common/CAMARA_common.yaml#/components/schemas/PhoneNumber"

        idDocument:
          type: string
          maxLength: 50
          description: Id number associated to the id_document of the customer stored on the Operator's system.

        idDocumentType:
          type: string
          maxLength: 50
          enum: [passport, national_id_card, residence_permit, diplomatic_id, driver_licence, social_security_id, other]
          description: Type of the official identity document provided.

        idDocumentExpiryDate:
          type: string
          format: date
          maxLength: 10
          description: Expiration date of the identity document (ISO 8601).

        bankAccountNumber:
          type: string
          maxLength: 50
          pattern: '^[A-Z]+:[A-Za-z0-9]+$'
          description: The bank account number maintained by the API Provider (Telco operator) to collect monthly subscription payments from the contract owner. The string is formatted as `PREFIX:VALUE`. The uppercase prefix before the colon (':') indicates the type of account number (e.g., IBAN, SWIFT), and the alphanumeric string after the colon represents the actual bank account number.

        name:
          type: string
          maxLength: 256
          description: Complete name of the customer stored on the Operator's system.  It is usually composed of first/given name and last/family/sur- name in a country.  Depending on the country, the order of first/give name and last/family/sur- name varies, and middle name could be included.  It can use givenName, middleNames, familyName and/or familyNameAtBirth. For example, in ESP, name+familyName; in NLD, it can be name+middleNames+familyName or name+middleNames+familyNameAtBirth, etc.

        givenName:
          type: string
          maxLength: 100
          description: First/given name or compound first/given name of the customer on the Operator's system.

        familyName:
          type: string
          maxLength: 150
          description: Last name, family name, or surname of the customer stored on the Operator's system.

        nameKanaHankaku:
          type: string
          maxLength: 256
          description: Complete name of the customer in Hankaku-Kana format (reading of name) for Japan, stored on the Operator's system.

        nameKanaZenkaku:
          type: string
          maxLength: 256
          description: Complete name of the customer in Zenkaku-Kana format (reading of name) for Japan, stored on the Operator's system.

        middleNames:
          type: string
          maxLength: 100
          description: Middle name/s of the customer stored on the Operator's system.

        familyNameAtBirth:
          type: string
          maxLength: 150
          description: Last/family/sur- name at birth of the customer stored on the Operator's system.

        address:
          type: string
          maxLength: 256
          description: Complete address of the customer stored on the Operator's system.  For some countries, it is built following the usual concatenation of parameters in a country, but for other countries, this is not the case.  For some countries, it can use streetName, streetNumber and/or houseNumberExtension. For example, in ESP, streetName+streetNumber; in NLD, it can be streetName+streetNumber or streetName+streetNumber+houseNumberExtension.

        streetName:
          type: string
          maxLength: 150
          description: Name of the street of the customer's address on the Operator's system.  It should not include the type of the street.

        streetNumber:
          type: string
          maxLength: 20
          description: The street number of the customer's address on the Operator's system.  Number identifying a specific property on the 'streetName'.

        postalCode:
          type: string
          maxLength: 20
          description: The postal code or Zip code of the customer's address, stored on the Operator's system.

        region:
          type: string
          maxLength: 100
          description: Region/prefecture of the customer's address, stored on the Operator's system.

        locality:
          type: string
          maxLength: 100
          description: Locality of the customer's address, stored on the Operator's system.

        country:
          description: Country of the customer's address. Format ISO 3166-1 alpha-2
          allOf:
            - $ref: '#/components/schemas/Iso3166Alpha2'

        houseNumberExtension:
          type: string
          maxLength: 20
          description: House number extension of the customer stored on the Operator's system.  Specific identifier of the house needed depending on the property type. For example, number of apartment in an apartment building.

        birthdate:
          type: string
          format: date
          maxLength: 10
          description: Birthdate of the customer, in ISO 8601 calendar date format (YYYY-MM-DD), stored on the Operator's system.

        email:
          type: string
          format: email
          maxLength: 254
          description: Email address of the customer in the RFC specified format (local-part@domain), stored on the Operator's system.

        gender:
          type: string
          maxLength: 6
          description: Gender of the customer stored on the Operator's system (Male/Female/Other).
          enum:
            - MALE
            - FEMALE
            - OTHER

        cityOfBirth:
          type: string
          maxLength: 100
          description: City where the customer was born.

        countryOfBirth:
          description: Country where the customer was born. Format ISO 3166-1 alpha-2.
          allOf:
            - $ref: '#/components/schemas/Iso3166Alpha2'

        nationality:
          description: ISO 3166-1 alpha-2 code of the customer’s nationality. In the case a customer has more than one nationality, it is supposed to be the nationality related to the ID document provided in the match request.
          allOf:
            - $ref: '#/components/schemas/Iso3166Alpha2'

  responses:
    Generic400:
      description: Bad Request
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 400
                  code:
                    enum:
                      - INVALID_ARGUMENT
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.

    Generic401:
      description: Unauthorized
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 401
                  code:
                    enum:
                      - UNAUTHENTICATED
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated and a new authentication is required
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials. A new authentication is required.

    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 403
                  code:
                    enum:
                      - PERMISSION_DENIED

          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.

    Generic404:
      description: Not found
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 404
                  code:
                    enum:
                      - IDENTIFIER_NOT_FOUND
          examples:
            GENERIC_404_IDENTIFIER_NOT_FOUND:
              description: The phone number is not associated with a CSP customer account
              value:
                status: 404
                code: IDENTIFIER_NOT_FOUND
                message: The phone number provided is not associated with a customer account

    Generic422:
      description: Unprocessable Content
      headers:
        x-correlator:
          $ref: "../common/CAMARA_common.yaml#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../common/CAMARA_common.yaml#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 422
                  code:
                    enum:
                      - SERVICE_NOT_APPLICABLE
                      - MISSING_IDENTIFIER
                      - UNNECESSARY_IDENTIFIER
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service is not applicable for the provided phone number
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not applicable for the provided phone number
            GENERIC_422_MISSING_IDENTIFIER:
              description: No phone number has been provided either explicitly or associated with the access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: No phone number has been provided
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              description: An explicit phone number has been provided when one is already associated with the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: An explicit phone number has been provided when one is already associated with the access token
